# Generated by Django 3.1.7 on 2021-05-29 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FiatWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(blank=True, max_length=11, null=True)),
                ('account_name', models.CharField(blank=True, max_length=256, null=True)),
                ('bank', models.CharField(blank=True, max_length=256, null=True)),
                ('balance', models.CharField(blank=True, default=0, max_length=18, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fiat Wallet',
                'verbose_name_plural': 'Fiat Wallets',
                'db_table': 'fiat_wallet',
            },
        ),
    ]
