# Generated by Django 3.1.7 on 2021-06-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiatwallet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fiatwallet',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='fiatwallet',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='fiatwallet',
            name='bank',
        ),
        migrations.AddField(
            model_name='fiatwallet',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
