# Generated by Django 3.1.7 on 2021-07-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiatwallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiatwallet',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fiatwallet',
            name='balance',
            field=models.FloatField(blank=True, default=0, max_length=18, null=True),
        ),
    ]
