# Generated by Django 3.1.7 on 2021-07-08 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiatwallet', '0002_auto_20210708_1226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fiatwallet',
            options={'verbose_name': 'Escrow Wallet', 'verbose_name_plural': 'Escrow Wallets'},
        ),
    ]
