# Generated by Django 3.1.7 on 2021-07-09 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fiatwallet', '0003_auto_20210708_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletTransactionsHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit')], default='Credit', max_length=300)),
                ('amount', models.FloatField(blank=True, default=0, max_length=18, null=True)),
                ('transaction_key', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fiatwallet.fiatwallet')),
            ],
            options={
                'verbose_name': 'Escrow Wallet Transaction',
                'verbose_name_plural': 'Escrow Wallet Transactions',
                'db_table': 'wallet_tranactions',
            },
        ),
    ]
