# Generated by Django 3.1.7 on 2021-07-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiatwallet', '0004_wallettransactionshistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransactionshistory',
            name='transaction_type',
            field=models.CharField(choices=[('Wallet Created', 'Wallet Created'), ('Credit', 'Credit'), ('Debit', 'Debit')], default='Credit', max_length=300),
        ),
    ]
