# Generated by Django 3.1.7 on 2021-07-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EarlyBirdAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('referral_code', models.CharField(max_length=10)),
                ('number_of_referrals', models.IntegerField(default=0)),
                ('base_url', models.URLField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Early Access',
                'verbose_name_plural': 'Early Access',
                'db_table': 'early_access',
            },
        ),
    ]
