# Generated by Django 3.1.7 on 2021-07-10 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='earlybirdaccess',
            options={'ordering': ('number_of_referrals',), 'verbose_name': 'Early Access', 'verbose_name_plural': 'Early Access'},
        ),
    ]
