# Generated by Django 3.1.7 on 2021-07-13 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0002_auto_20210710_0250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='earlybirdaccess',
            options={'ordering': ('-number_of_referrals',), 'verbose_name': 'Early Access', 'verbose_name_plural': 'Early Access'},
        ),
    ]
