# Generated by Django 3.1.7 on 2021-08-24 03:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('referrals', '0003_auto_20210713_0602'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReferrals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_referrals', models.IntegerField(default=0)),
                ('base_url', models.URLField()),
                ('earnings', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referrals',
                'verbose_name_plural': 'Referrals',
                'db_table': 'referrals',
                'ordering': ('-number_of_referrals',),
            },
        ),
    ]
