# Generated by Django 3.1.7 on 2021-06-28 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='P2PTrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactions', models.PositiveIntegerField(default=0)),
                ('trade_listed_as', models.CharField(choices=[('I WANT TO BUY', 'I WANT TO BUY'), ('I WANT TO SELL', 'I WANT TO SELL')], default='I WANT TO SELL', max_length=20)),
                ('creator_rate_in_dollar', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('crypto_trading_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('min_trading_amount_in_fiat', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('max_trading_amount_in_fiat', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('asset_to_trade', models.CharField(choices=[('ETH', 'ETH'), ('BTC', 'BTC'), ('USDT', 'USDT'), ('DOGE', 'DOGE'), ('LTC', 'LTC')], default='BTC', max_length=20)),
                ('price_slippage', models.DecimalField(decimal_places=3, default=1.0, help_text='standard 1 dollar rate', max_digits=4)),
                ('min_slippage', models.DecimalField(decimal_places=3, default=0.98, help_text='minimum less than 1 dollar', max_digits=4)),
                ('max_slippage', models.DecimalField(decimal_places=3, default=1.02, help_text='maximum above 1 dollar', max_digits=4)),
                ('active', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=300, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('trade_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'P2P Trade',
                'verbose_name_plural': 'P2P Trades',
                'db_table': 'p2p',
            },
        ),
        migrations.CreateModel(
            name='P2PTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_key', models.CharField(blank=True, max_length=300, null=True)),
                ('crypto_unit_transacted', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True)),
                ('fiat_paid', models.CharField(blank=True, max_length=300, null=True)),
                ('status', models.CharField(choices=[('RUNNING', 'RUNNING'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED'), ('ON_APPEAL', 'ON_APPEAL')], default='RUNNING', max_length=20)),
                ('slug', models.SlugField(blank=True, max_length=300, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p2p.p2ptrade')),
                ('trade_visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_viewer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'P2P Trade Transactions',
                'verbose_name_plural': 'P2P Trade Transactions',
                'db_table': 'p2p_transaction',
            },
        ),
    ]
