# Generated by Django 3.1.7 on 2021-07-18 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='P2PTradeCoreSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escrow_fee', models.FloatField(default=0.8)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'P2P Trade Settings',
                'verbose_name_plural': 'P2P Trade Settings',
                'db_table': 'p2p_settings',
            },
        ),
        migrations.AlterField(
            model_name='p2ptransaction',
            name='status',
            field=models.CharField(choices=[('CREATED AND RUNNING', 'CREATED AND RUNNING'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED'), ('ON_APPEAL', 'ON_APPEAL')], default='RUNNING', max_length=20),
        ),
    ]
