# Generated by Django 3.1.7 on 2021-07-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p', '0002_auto_20210717_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='p2ptrade',
            name='crypto_trading_amount',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='p2ptrade',
            name='max_trading_amount_in_fiat',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='p2ptrade',
            name='min_trading_amount_in_fiat',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='p2ptransaction',
            name='crypto_unit_transacted',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='p2ptransaction',
            name='status',
            field=models.CharField(choices=[('CREATED AND RUNNING', 'CREATED AND RUNNING'), ('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED'), ('ON_APPEAL', 'ON_APPEAL')], default='CREATED AND RUNNING', max_length=20),
        ),
    ]
