# Generated by Django 3.1.7 on 2021-05-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p', '0002_auto_20210529_0622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peertopeertrade',
            name='crypto_amount',
        ),
        migrations.AddField(
            model_name='peertopeertrade',
            name='crypto_trading_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='peertopeertrade',
            name='max_trading_amount_in_fiat',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='peertopeertrade',
            name='min_trading_amount_in_fiat',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='peertopeertrade',
            name='asset_to_trade',
            field=models.CharField(choices=[('ETHEREUM', 'ETHEREUM'), ('BITCOIN', 'BITCOIN'), ('USDT', 'USDT'), ('DOGE', 'DOGE'), ('LITECOIN', 'LITECOIN'), ('DASH', 'DASH'), ('BITCOIN CASH', 'BITCOIN CASH')], default='BITCOIN', max_length=20),
        ),
    ]
