# Generated by Django 3.1.7 on 2021-07-28 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p', '0003_auto_20210718_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='p2ptrade',
            name='owner_cancel_trade',
            field=models.BooleanField(default=False),
        ),
    ]
