# Generated by Django 3.1.7 on 2021-05-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2p', '0004_auto_20210529_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peertopeertrade',
            name='trade_listed_as',
            field=models.CharField(choices=[('I WANT TO BUY', 'I WANT TO BUY'), ('I WANT TO SELL', 'I WANT TO SELL')], default='I WANT TO SELL', max_length=20),
        ),
    ]
