# Generated by Django 3.1.7 on 2021-06-15 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p2p', '0006_auto_20210615_1132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='p2ptransaction',
            options={'verbose_name': 'P2P Trade Transactions', 'verbose_name_plural': 'P2P Trade Transactions'},
        ),
    ]
