# Generated by Django 3.1.7 on 2021-06-28 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoinGecko',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=50)),
                ('price', models.FloatField(blank=True, default=0, null=True)),
                ('rank', models.IntegerField(blank=True, default=0, null=True)),
                ('image', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='USD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=50)),
                ('volume_24h', models.CharField(max_length=50)),
                ('percent_change1h', models.CharField(max_length=50)),
                ('percent_change24h', models.CharField(max_length=50)),
                ('percent_change7d', models.CharField(max_length=50)),
                ('percent_change30d', models.CharField(max_length=50)),
                ('percent_change60d', models.CharField(max_length=50)),
                ('percent_change90d', models.CharField(max_length=50)),
                ('market_cap', models.CharField(max_length=50)),
                ('last_updated', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coins.usd')),
            ],
        ),
        migrations.CreateModel(
            name='CoinCMC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=50)),
                ('number_of_market_pairs', models.CharField(max_length=50)),
                ('date_added', models.CharField(max_length=50)),
                ('max_supply', models.CharField(max_length=50)),
                ('circulating_supply', models.CharField(max_length=50)),
                ('total_supply', models.CharField(max_length=50)),
                ('platform', models.CharField(max_length=50)),
                ('cmc_rank', models.IntegerField(default=0)),
                ('last_updated', models.CharField(max_length=50)),
                ('quote', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coins.quote')),
            ],
        ),
    ]
