# Generated by Django 3.1.7 on 2021-06-26 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinGecko',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('rank', models.IntegerField(default=0)),
                ('image', models.CharField(max_length=300)),
            ],
        ),
        migrations.RenameModel(
            old_name='Coin',
            new_name='CoinCMC',
        ),
    ]
