# Generated by Django 3.1.7 on 2021-06-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0002_auto_20210626_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coingecko',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coingecko',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='coingecko',
            name='rank',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
