# Generated by Django 3.1.7 on 2021-06-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0004_remove_coin_price_change_percentage_1h_in_usd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='coin_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
