# Generated by Django 3.1.7 on 2021-06-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0005_auto_20210630_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='all_time_high_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='all_time_low_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
