# Generated by Django 3.1.7 on 2021-06-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0006_auto_20210630_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='market_cap',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='total_volume',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
