# Generated by Django 3.1.7 on 2021-06-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0007_auto_20210630_0431'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='price_change_in_the_last_1hr',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
