# Generated by Django 3.1.7 on 2021-03-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country_flag',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ssn',
            field=models.CharField(blank=True, help_text='Social Security Number/National Identity Number', max_length=20, null=True),
        ),
    ]
