# Generated by Django 3.1.7 on 2021-07-05 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_favouriteassets'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favouriteassets',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='favouriteassets',
            name='slug',
        ),
    ]
