# Generated by Django 3.1.7 on 2021-05-29 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userlock'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='trades',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
