# Generated by Django 3.1.7 on 2021-03-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0002_auto_20210328_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiatrate',
            name='dollar_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
