# Generated by Django 3.1.7 on 2021-06-10 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(blank=True, max_length=299, null=True)),
                ('receiver', models.CharField(blank=True, max_length=299, null=True)),
                ('amount', models.CharField(blank=True, max_length=299, null=True)),
                ('transaction_hash', models.CharField(blank=True, max_length=299, null=True)),
                ('asset_type', models.CharField(blank=True, max_length=299, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
