# Generated by Django 3.1.7 on 2021-04-18 17:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EthereumWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Ethereum', max_length=256)),
                ('short_name', models.CharField(default='ETH', max_length=12)),
                ('icon', models.URLField(blank=True, null=True)),
                ('encrypted_private_key', models.TextField(blank=True, null=True)),
                ('public_key', models.CharField(blank=True, max_length=256, null=True)),
                ('frozen', models.BooleanField(default=False)),
                ('amount', models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=999, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ethereum Wallet',
                'verbose_name_plural': 'Ethereum Wallets',
                'db_table': 'ethereum_wallet',
            },
        ),
    ]
