# Generated by Django 3.1.7 on 2021-03-25 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BitcoinCashWallet',
        ),
        migrations.RemoveField(
            model_name='bitcoinwallet',
            name='user',
        ),
        migrations.DeleteModel(
            name='Dodgecoin',
        ),
        migrations.DeleteModel(
            name='KleverWallet',
        ),
        migrations.DeleteModel(
            name='LitecoinWallet',
        ),
        migrations.DeleteModel(
            name='Ripple',
        ),
        migrations.DeleteModel(
            name='TronWallet',
        ),
        migrations.DeleteModel(
            name='VendWallet',
        ),
        migrations.DeleteModel(
            name='BitcoinWallet',
        ),
    ]
