# Generated by Django 3.1.7 on 2021-03-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_auto_20210325_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='ethereum_wallet',
            name='name',
            field=models.CharField(default='ETH', max_length=256),
        ),
    ]
