# Generated by Django 3.1.7 on 2021-05-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_auto_20210502_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='ethereumwallet',
            name='available',
            field=models.CharField(blank=True, default=0, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='ethereumwallet',
            name='previous_bal',
            field=models.CharField(blank=True, default=0, max_length=18, null=True),
        ),
    ]
