# Generated by Django 3.1.7 on 2021-03-28 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_ethereum_wallet_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ethereum_wallet',
            name='name',
            field=models.CharField(default='Ethereum', max_length=256),
        ),
    ]
