# Generated by Django 3.1.7 on 2021-03-30 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0004_auto_20210328_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='ethereum_wallet',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=999, null=True),
        ),
        migrations.AddField(
            model_name='ethereum_wallet',
            name='frozen',
            field=models.BooleanField(default=False),
        ),
    ]
