# Generated by Django 3.1.7 on 2021-05-07 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wallets', '0005_vendtokenwallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitcoinWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Bitcoin', max_length=256)),
                ('short_name', models.CharField(default='BTC', max_length=12)),
                ('icon', models.URLField(blank=True, null=True)),
                ('private_key', models.TextField(blank=True, null=True)),
                ('public_key', models.CharField(blank=True, max_length=256, null=True)),
                ('address', models.CharField(blank=True, max_length=256, null=True)),
                ('wif', models.CharField(blank=True, max_length=256, null=True)),
                ('previous_bal', models.CharField(blank=True, default=0, max_length=18, null=True)),
                ('available', models.CharField(blank=True, default=0, max_length=18, null=True)),
                ('frozen', models.BooleanField(default=False)),
                ('amount', models.CharField(blank=True, default=0, max_length=18, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bitcoin Wallet',
                'verbose_name_plural': 'Bitcoin Wallets',
                'db_table': 'bitcoin_wallet',
            },
        ),
    ]
