# Generated by Django 3.1.7 on 2021-05-30 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0007_bitcoincashwallet_dashwallet_dogecoinwallet_litecoinwallet'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BitcoinCashWallet',
        ),
    ]
