# Generated by Django 3.1.7 on 2021-06-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mono', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountlinkage',
            name='fullName',
            field=models.CharField(blank=True, max_length=299, null=True),
        ),
    ]
